global:
  dynamic:
    plugins:
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-bulk-import
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-bulk-import-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-tech-radar
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-tekton
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-topology
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-acr
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-jfrog-artifactory
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-nexus-repository-manager
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-quay
        disabled: false

upstream:
  backstage:
    image:
      registry: registry.redhat.io
      repository: rhdh/rhdh-hub-rhel9@sha256
      tag: ccc2f05dd6dacbe9b39bbe5b4774ef9d61b872fa7c26e47c0c63d260920ad436
      pullPolicy: Always

    appConfig:
      app:
        brainding:
          theme:
            options:
              cards: mui

      catalog:
        rules:
          - allow: [Component, System, API, Resource, Location]
        locations:
          - type: url
            target: https://github.com/christoph-jerolimov/janus/blob/main/test-catalog/all.yaml
            rules:
              - allow: [Component, System, API, Resource, Location, User, Group]

      dynamicPlugins:
        frontend:
          default.main-menu-items:
            menuItems:
              default.home:
                title: Home (changed)

          janus-idp.backstage-plugin-dynamic-home-page:
            mountPoints:
              - mountPoint: home.page/cards
                importName: SearchBar
                config:
                  layouts:
                    xl: { w: 10, h: 1, x: 1 }
                    lg: { w: 10, h: 1, x: 1 }
                    md: { w: 10, h: 1, x: 1 }
                    sm: { w: 10, h: 1, x: 1 }
                    xs: { w: 12, h: 1 }
                    xxs: { w: 12, h: 1 }
              - mountPoint: home.page/cards
                importName: CatalogStarredEntitiesCard
                config:
                  layouts:
                    xl: { w: 6, h: 4 }
                    lg: { w: 6, h: 4 }
                    md: { w: 6, h: 4 }
                    sm: { w: 12, h: 4 }
                    xs: { w: 12, h: 4 }
                    xxs: { w: 12, h: 4 }
              - mountPoint: home.page/cards
                importName: Placeholder
                config:
                  layouts:
                    xl: { w: 1, h: 1 }
                    lg: { w: 1, h: 1 }
                    md: { w: 1, h: 1 }
                    sm: { w: 1, h: 1 }
                    xs: { w: 1, h: 1 }
                    xxs: { w: 1, h: 1 }
                  props:
                    showBorder: true
                    debugContent: '1 janus'
              - mountPoint: home.page/cards
                importName: Placeholder
                config:
                  layouts:
                    xl: { w: 1, h: 1, x: 1 }
                    lg: { w: 1, h: 1, x: 1 }
                    md: { w: 1, h: 1, x: 1 }
                    sm: { w: 1, h: 1, x: 1 }
                    xs: { w: 1, h: 1, x: 1 }
                    xxs: { w: 1, h: 1, x: 1 }
                  props:
                    showBorder: true
                    debugContent: '2'
              - mountPoint: home.page/cards
                importName: Placeholder
                config:
                  layouts:
                    xl: { w: 1, h: 1 }
                    lg: { w: 1, h: 1 }
                    md: { w: 1, h: 1 }
                    sm: { w: 1, h: 1 }
                    xs: { w: 1, h: 1 }
                    xxs: { w: 1, h: 1 }
                  props:
                    showBorder: true
                    debugContent: '3'
      
              - mountPoint: home.page/cards
                importName: Placeholder
                config:
                  layouts:
                    xl: { w: 12, h: 1 }
                    lg: { w: 12, h: 1 }
                    md: { w: 12, h: 1 }
                    sm: { w: 12, h: 1 }
                    xs: { w: 12, h: 1 }
                    xxs: { w: 12, h: 1 }
                  props:
                    showBorder: true
                    debugContent: '4'
      
              - mountPoint: home.page/cards
                importName: Placeholder
                config:
                  layouts:
                    xl: { w: 1, h: 1 }
                    lg: { w: 1, h: 1 }
                    md: { w: 1, h: 1 }
                    sm: { w: 1, h: 1 }
                    xs: { w: 1, h: 1 }
                    xxs: { w: 1, h: 1 }
                  props:
                    showBorder: true
                    debugContent: '5'
              - mountPoint: home.page/cards
                importName: Placeholder
                config:
                  layouts:
                    xl: { w: 1, h: 1, x: 1 }
                    lg: { w: 1, h: 1, x: 1 }
                    md: { w: 1, h: 1, x: 1 }
                    sm: { w: 1, h: 1, x: 1 }
                    xs: { w: 1, h: 1, x: 1 }
                    xxs: { w: 1, h: 1, x: 1 }
                  props:
                    showBorder: true
                    debugContent: '6'
              - mountPoint: home.page/cards
                importName: FeaturedDocsCard
              - mountPoint: home.page/cards
                importName: Headline
                config:
                  layouts:
                    xl: { h: 1 }
                    lg: { h: 1 }
                    md: { h: 1 }
                    sm: { h: 1 }
                    xs: { h: 1 }
                    xxs: { h: 1 }
                  props:
                    title: Important info
              - mountPoint: home.page/cards
                importName: Headline
                config:
                  layouts:
                    xl: { h: 1 }
                    lg: { h: 1 }
                    md: { h: 1 }
                    sm: { h: 1 }
                    xs: { h: 1 }
                    xxs: { h: 1 }
                  props:
                    title: Important info
                    align: right
              - mountPoint: home.page/cards
                importName: MarkdownCard
                config:
                  layouts:
                    xl: { w: 6, h: 3 }
                    lg: { w: 6, h: 3 }
                    md: { w: 6, h: 3 }
                    sm: { w: 6, h: 3 }
                    xs: { w: 6, h: 3 }
                    xxs: { w: 6, h: 3 }
                  props:
                    title: Company links
                    content: |
                      ### RHDH
      
                      * [Website](https://developers.redhat.com/rhdh/overview)
                      * [Documentation](https://docs.redhat.com/en/documentation/red_hat_developer_hub/)
                      * [GitHub Showcase](https://github.com/janus-idp/backstage-showcase)
                      * [GitHub Plugins](https://github.com/janus-idp/backstage-plugins)
                      * [Website](https://developers.redhat.com/rhdh/overview)
                      * [Documentation](https://docs.redhat.com/en/documentation/red_hat_developer_hub/)
                      * [GitHub Showcase](https://github.com/janus-idp/backstage-showcase)
                      * [GitHub Plugins](https://github.com/janus-idp/backstage-plugins)
              - mountPoint: home.page/cards
                importName: Markdown
                config:
                  layouts:
                    xl: { w: 6, h: 3, x: 6 }
                    lg: { w: 6, h: 3, x: 6 }
                    md: { w: 6, h: 3, x: 6 }
                    sm: { w: 6, h: 3, x: 6 }
                    xs: { w: 6, h: 3, x: 6 }
                    xxs: { w: 6, h: 3, x: 6 }
                  props:
                    title: Important company links
                    content: |
                      ### RHDH
      
                      * [Website](https://developers.redhat.com/rhdh/overview)
                      * [Documentation](https://docs.redhat.com/en/documentation/red_hat_developer_hub/)
                      * [GitHub Showcase](https://github.com/janus-idp/backstage-showcase)
                      * [GitHub Plugins](https://github.com/janus-idp/backstage-plugins)
                      * [Website](https://developers.redhat.com/rhdh/overview)
                      * [Documentation](https://docs.redhat.com/en/documentation/red_hat_developer_hub/)
                      * [GitHub Showcase](https://github.com/janus-idp/backstage-showcase)
                      * [GitHub Plugins](https://github.com/janus-idp/backstage-plugins)
              - mountPoint: home.page/cards
                importName: QuickAccessCard
                config:
                  layouts:
                    xl: { h: 8 }
                    lg: { h: 8 }
                    md: { h: 8 }
                    sm: { h: 8 }
                    xs: { h: 8 }
                    xxs: { h: 8 }
              - mountPoint: home.page/cards
                importName: TopVisitedCard
                config:
                  layouts:
                    xl: { w: 6, h: 4 }
                    lg: { w: 6, h: 4 }
                    md: { w: 6, h: 4 }
                    sm: { w: 6, h: 4 }
                    xs: { w: 6, h: 4 }
                    xxs: { w: 6, h: 4 }
              - mountPoint: home.page/cards
                importName: RecentlyVisitedCard
                config:
                  layouts:
                    xl: { w: 6, h: 4, x: 6 }
                    lg: { w: 6, h: 4, x: 6 }
                    md: { w: 6, h: 4, x: 6 }
                    sm: { w: 6, h: 4, x: 6 }
                    xs: { w: 6, h: 4, x: 6 }
                    xxs: { w: 6, h: 4, x: 6 }

      permission:
        enabled: true
        rbac:
          pluginsWithPermission:
            # - kubernetes
            - bulk-import
            - catalog
            # - scaffolder
            # - policy
          admin:
            superUsers:
              - name: user:default/christoph-jerolimov

  # reduce memoty usage
  postgresql:
    primary:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 256Mi
